# Visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge
timezone: Asia/Ho_Chi_Minh
repository: ethan605/dev-with-ethan

disqus: 'dev-with-ethan'
google_analytics: 'UA-49527418-4'

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Dev With Ethan

title: Dev With Ethan
description: Blog Lập trình cùng Ethan
url: dev.ethanify.me
author:
  name: Ethan605
  email: thanhnx.605@gmail.com
  github: ethan605
  twitter: '@ethan605'
  linkedin: ethan605
  bio: Passionate about creating awesome products that help plenty of people improving their lives.
  email_md5: 48698fe64e24d81467ccc86d3083052d
twitter:
  username: ethan605
facebook:
  app_id: 1783427568545702
  admins: 1119670477
logo: http://www.gravatar.com/avatar/48698fe64e24d81467ccc86d3083052d

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

gems:
  - github-pages
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap