# Visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
permalink: /:categories/:title
post_dirs: false

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
highlighter: rouge
timezone: Asia/Ho_Chi_Minh
repository: ethan605/dev-with-ethan

disqus: 'dev-with-ethan'
google_analytics: 'UA-49527418-4'

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Dev With Ethan
      image:
        path: /assets/media/ethanify.png
        width: 200
        height: 200

title: Dev With Ethan
description: Blog Lập trình cùng Ethan
url: http://dev.ethanify.me
author:
  name: Ethan605
  email: thanhnx.605@gmail.com
  github: ethan605
  twitter: '@ethan605'
  linkedin: ethan605
  bio: Passionate about creating awesome products that help plenty of people improving their lives.
  email_md5: 48698fe64e24d81467ccc86d3083052d
twitter:
  username: ethan605
facebook:
  app_id: 1783427568545702
  admins: 1119670477
  publisher: 1119670477

rss_path: feed.xml
categories_path: categories
tags_path: tags

BASE_PATH:

gems:
  - github-pages
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap